fos_rest:
  routing_loader:
    default_format: json
    include_format: false
    prefix_methods: false

  view:
    view_response_listener: true

  # zone:
  #   - { path: ^/api(?!/doc$) }

  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: 'json' }

  # param_fetcher_listener: force
  disable_csrf_role: ROLE_USER